name: 'test-gh-action-rl-protect-dummy'
author: 'Maarten Boot'
description: 'create a dummy action using python'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  item-to-scan:
    description: 'Path to the file or folder'
    type: string
    required: true

  profile:
    description: 'what profile to use: org | group | file'
    type: string
    required: false
    default: ""

  log-file:
    description: 'path to a log file'
    required: false
    default: ""
    type: string

  check-deps:
    description: 'check dependencies'
    required: false
    default: ""
    type: string
    # values: comma separated: 'develop', 'release', 'optional', 'transitive'

  concise:
    description: 'when selecting the concise reporting is the list shortened to final outcomes only.'
    required: false
    default: false
    type: bool

  rl-server:
  	description: 'the server to connect to'
  	type: string
  	required: false
  	default: ""
  rl-token:
  	description: 'authentication token' # will be passed as secret
  	type: string
  	required: false
  	default: ""

  # optional proxy
  proxy-server:
    description: 'An optional proxy server to use'
    required: false
    default: ""
    type: string
  proxy-port:
    description: 'An optional proxy server port to use'
    required: false
    default: ""
    type: string
  proxy-user:
    description: 'An optional proxy server user to use'
    required: false
    default: ""
    type: string
  proxy-password:
    description: 'An optional proxy server password to use'
    required: false
    default: ""
    type: string
    
  return-status:
    description: 'Set command return status to fail if there is any items found'
    required: false
    default: false
    type: bool
  no-color:
    description: 'Do not output color to terminal or log'
    required: false
    default: false
    type: bool

  rl-verbose:
    description: 'Make the scanner more verbose'
    required: false
    default: false
    type: bool

outputs:
  description:
    description: 'The result of the action: a string terminating in FAIL or PASS'
    value: ${{ steps.scan.outputs.description }}
  status:
    description: 'The single word result of the action: success, failure or error'
    value: ${{ steps.scan.outputs.status }}

runs:
  using: "composite"

  steps:
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    
    - name: Dummy rl-protect using python
      id: scan
      run: |
        pip install rl-deploy
        rl-deploy --version
        echo "description=This is a message"  >> $GITHUB_OUTPUT
        echo "status=success"                 >> $GITHUB_OUTPUT
      shell: bash
    - id: scan
      run: ${{ github.action_path }}/run-scanner.sh
      shell: bash
      env:
        REPORT_PATH: ${{ inputs.report-path }}
        MY_ARTIFACT_TO_SCAN_PATH: ${{ inputs.artifact-to-scan }}
        RL_STORE: ${{ inputs.rl-store}}
        RL_PACKAGE_URL: ${{ inputs.rl-package-url }}
        RL_DIFF_WITH: ${{ inputs.rl-diff-with }}
        RL_VERBOSE: ${{ inputs.rl-verbose }}
        RLSECURE_PROXY_SERVER: ${{ inputs.rl-proxy-server }}
        RLSECURE_PROXY_PORT: ${{ inputs.rl-proxy-port }}
        RLSECURE_PROXY_USER: ${{ inputs.rl-proxy-user }}
        RLSECURE_PROXY_PASSWORD: ${{ inputs.rl-proxy-password }}
    # -------------------------------------
    # Return the proper exit status
    - name: Set the exit status
      if: always()
      shell: bash
      run: |
        case "${{ steps.scan.outputs.status }}" in
        success)
          exit 0
          ;;
        failure)
          exit 1
          ;;
        *)
          exit 101
          ;;
        esac
