name: 'test-gh-action-rl-protect-dummy'
author: 'Maarten Boot'
description: 'create a dummy action using python'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  artifact-to-scan:
    description: 'Path to the package file (artifact) you want to scan'
    required: true

outputs:
  description:
    description: 'The result of the action: a string terminating in FAIL or PASS'
    value: ${{ steps.scan.outputs.description }}
  status:
    description: 'The single word result of the action: success, failure or error'
    value: ${{ steps.scan.outputs.status }}

runs:
  using: "composite"

  steps:
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    
    - name: Dummy rl-protect using python
      id: scan
      run: |
        pip install rl-deploy
        rl-deploy --version
        echo "description=This is a message"  >> $GITHUB_OUTPUT
        echo "status=success"                 >> $GITHUB_OUTPUT
      shell: bash

    # -------------------------------------
    # Return the proper exit status
    - name: Set the exit status
      if: always()
      shell: bash
      run: |
        case "${{ steps.scan.outputs.status }}" in
        success)
          exit 0
          ;;
        failure)
          exit 1
          ;;
        *)
          exit 101
          ;;
        esac
