name: 'test-gh-action-rl-protect-dummy'
author: 'Maarten Boot'
description: 'create a dummy action using python'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  rl-item-to-scan:
    description: 'Path to the file or folder'
    type: string
    required: true

  rl-profile:
    description: 'what profile to use: org | group | file'
    type: string
    required: false
    default: ""

  rl-log-file:
    description: 'path to a log file'
    required: false
    default: ""
    type: string

  rl-check-deps:
    description: 'check dependencies'
    required: false
    default: ""
    type: string
    # values: comma separated: 'develop', 'release', 'optional', 'transitive'

  rl-concise:
    description: 'when selecting the concise reporting is the list shortened to final outcomes only.'
    required: false
    default: false
    type: bool

  rl-server:
    description: 'the server to connect to'
    type: string
    required: false
    default: ""
  # rl-tone is passed via the env as RL_TOKEN

  # optional proxy
  rl-proxy-server:
    description: 'An optional proxy server to use'
    required: false
    default: ""
    type: string
  rl-proxy-port:
    description: 'An optional proxy server port to use'
    required: false
    default: ""
    type: string
  rl-proxy-user:
    description: 'An optional proxy server user to use'
    required: false
    default: ""
    type: string
  rl-proxy-password:
    description: 'An optional proxy server password to use'
    required: false
    default: ""
    type: string

  rl-return-status:
    description: 'Set command return status to fail if there is any items found'
    required: false
    default: false
    type: bool
  rl-no-color:
    description: 'Do not output color to terminal or log'
    required: false
    default: false
    type: bool

  rl-verbose:
    description: 'Make the scanner more verbose'
    required: false
    default: false
    type: bool

outputs:
  description:
    description: 'The result of the action: a string terminating in FAIL or PASS'
    value: ${{ steps.scan.outputs.description }}
  status:
    description: 'The single word result of the action: success, failure or error'
    value: ${{ steps.scan.outputs.status }}

runs:
  using: "composite"

  steps:
    # -------------------------------------
    # install python
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    # -------------------------------------
    # Run the run-scan.sh script
    # RL_TOKEN is passed via the env already
    - name: Dummy rl-protect using python
      id: scan
      run: ${{ github.action_path }}/run-scan.sh
      shell: bash
      env:
        RL_ITEM_TO_SCAN: ${{ inputs.rl-item-to-scan }}
        RL_PROFILE: ${{ inputs.rl-profile}}
        RL_LOG_FILE: ${{ inputs.rl-log-file }}
        RL_CHECK_DEPS: ${{ inputs.rl-check-deps }}
        RL_CONCISE: ${{ inputs.rl-concise }}
        RL_SERVER: ${{ inputs.rl-server }}
        RL_PROXY_SERVER: ${{ inputs.rl-proxy-server }}
        RL_PROXY_PORT: ${{ inputs.rl-proxy-port }}
        RL_PROXY_USER: ${{ inputs.rl-proxy-user }}
        RL_PROXY_PASSWORD: ${{ inputs.rl-proxy-password }}
        RL_RETURN_STATUS: ${{ inputs.rl-return-status }}
        RL_NO_COLOR: ${{ inputs.rl-no-color }}
        RL_VERBOSE: ${{ inputs.rl-verbose }}

    # -------------------------------------
    # Return the proper exit status
    - name: Set the exit status
      if: always()
      shell: bash
      run: |
        case "${{ steps.scan.outputs.status }}" in
        success)
          exit 0
          ;;
        failure)
          exit 1
          ;;
        *)
          exit 101
          ;;
        esac
